#' Output the result of Category level intensity analysis as csv.
#' @details Gets the output of \code{CIA} function and the path variable and generate a csv report called "CategoryLevelIntensityAnalysis.csv". The output will be stored in "CSVOutput" directory in path direction.
#' @param CIA.output Output list generated by \code{CIA} function.
#' @param path A charachter variable showing the path to where the user wants to store the csv output.
#' @return The output is a CSV file.
#' @export


CIA2csv <- function(CIA.output, path){

  parameters <- reqpar(time.points)
  # Get the current working directory
  wd.old <- getwd()
  # Set the new working directory to the defined path
  setwd(path)

  if (file.exists("./CSVOutput")){
    suppressWarnings(file.remove("./CSVOutput/CategoryLevelIntensityAnalysis.csv", showWarnings = FALSE ))
  } else {
    # Create a subdirectory named "output" in the working directory to save the analysis output
    dir.create("CSVOutput", showWarnings = FALSE)
  }

  for (i in 1: as.integer(parameters$number.of.intervals)){
    # Making a data frame for output of category level analysis for each interval
    out.dataframe.1 <- cbind(CIA.output$Annual.Gross.Loss[[i]], CIA.output$Annual.Gross.Gain[[i]], CIA.output$Annual.Loss.Intensity[[i]], CIA.output$Annual.Gain.Intensity[[i]],
                             CIA.output$Uniform.Category.Intensity[i], CIA.output$Loss.Behavior[[i]], CIA.output$Gain.Behavior[[i]])

    colnames(out.dataframe.1) <- c("Gross Loss", "Gross Gain","Loss Intensity","Gain Intensity",
                                   "Uniform Category Intensity","Loss Behavior","Gain Behavior")

    rownames(out.dataframe.1) <- paste(categories)
    category.level.header <- paste("Category level Intensity Analysis for interval: ", as.character(parameters$initial.times[i]),
                                   as.character("-"),as.character(parameters$subsequent.times[i]),sep =" ")

    cat(category.level.header, "\n", file= "./CSVOutput/CategoryLevelIntensityAnalysis.csv",append = TRUE)
    category.file <- "./CSVOutput/CategoryLevelIntensityAnalysis.csv"
    write.table(out.dataframe.1, file = category.file , append = TRUE, col.names=NA ,quote = TRUE, sep = ",")
    cat("\n", file= category.file ,append = TRUE)
  }
  # Set back the working directory to its original path
  setwd(wd.old)
}
