#' Output the result of Interval level intensity analysis as csv.
#' @details Gets the output of \code{IIA} function and the path variable and generate a csv report called "IntervalLevelIntensityAnalysis.csv". The output will be stored in "CSVOutput" directory in path direction.
#' @param IIA.output Output list generated by \code{IIA} function.
#' @param path A charachter variable showing the path to where the user wants to store the csv output.
#' @return The output is a CSV file.
#' @export


IIA2csv <- function(IIA.output, path){

  parameters <- reqpar(time.points)
  # Get the current working directory
  wd.old <- getwd()
  # Set the new working directory to the defined path
  setwd(path)

  if (file.exists("./CSVOutput")){
    suppressWarnings(file.remove("./CSVOutput/IntervalLevelIntensityAnalysis.csv", showWarnings = FALSE ))
  } else {
    # Create a subdirectory named "output" in the working directory to save the analysis output
    dir.create("CSVOutput", showWarnings = FALSE)
  }
  out.dataframe.3 <- cbind(IIA.output$Change.Size, IIA.output$Uniform.Intensity.of.Change, IIA.output$Uniform.Change.all.Intervals, IIA.output$Interval.Behavior)
  colnames(out.dataframe.3) <- c( "Change Size", "Annual change","Uniform Change across Intervals", "Interval Behavior")
  rownames(out.dataframe.3) <- paste(parameters$interval.name)

  interval.file <- "./CSVOutput/IntervalLevelIntensityAnalysis.csv"
  write.table(out.dataframe.3, file = interval.file, append = FALSE, col.names=NA ,quote = TRUE, sep = ",", fileEncoding = "UTF-16LE")

  # Set back the working directory to its original path
  setwd(wd.old)
}
