#' Output the result of transition level intensity analysis as csv.
#' @details Gets the output of \code{TIA} function and the path variable and generate a csv report called "TransitionLevelIntensityAnalysis.csv". The output will be stored in "CSVOutput" directory in the path direction.
#' @param TIA.output Output list generated by \code{TIA} function.
#' @param path A charachter variable showing the path to where the user wants to store the csv output.
#' @return The output is a CSV file.
#' @export


TIA2csv <- function(TIA.output, path){

  parameters <- reqpar(time.points)
  # Get the current working directory
  wd.old <- getwd()
  # Set the new working directory to the defined path
  setwd(path)

  if (file.exists("./CSVOutput")){
    suppressWarnings(file.remove("./CSVOutput/TransitionLevelIntensityAnalysis.csv", showWarnings = FALSE ))
  } else {
    # Create a subdirectory named "output" in the working directory to save the analysis output
    dir.create("CSVOutput", showWarnings = FALSE)
  }

  for (i in 1: as.integer(parameters$number.of.intervals)){
    transition.level.header <- paste("Transition level Intensity Analysis for interval: ",
                                     as.character(parameters$initial.times[i]),as.character("-"),as.character(parameters$subsequent.times[i]),sep =" ")
    cat(transition.level.header, "\n", file= "./CSVOutput/TransitionLevelIntensityAnalysis.csv",append = TRUE)

    for (x in 1: ncol(TIA.output$Annual.Transition.Intensity[[i]])){
      out.dataframe.2 <- cbind(na.omit(TIA.output$Annual.Transition.Size[[i]][ ,x]),na.omit(TIA.output$Annual.Transition.Intensity[[i]][ ,x]),
                               rep(TIA.output$Uniform.Transition[[i]][x],each= length(categories)-1),na.omit(TIA.output$Transition.Behavior.for.Gain[[i]][ ,x]))
      header5 <- categories[-x]
      rownames(out.dataframe.2) <- paste(header5)
      colnames(out.dataframe.2) <- c(paste("Annual Transition Size for Gain of", categories[x]), paste("Transition Intensity for Gain of ",categories[x]),
                                     "Uniform Transition Intensity",paste("Transition Behavior for Gain of ",categories[x]))
      # Add a header showing the interval for each dataframe
      # Write the transition level intensity analysis to a csv file
      transition.file <- "./CSVOutput/TransitionLevelIntensityAnalysis.csv"
      write.table(out.dataframe.2, file = transition.file, append = TRUE, col.names=NA ,quote = TRUE, sep = ",")
      cat("\n", file= transition.file ,append = TRUE)
    }
  }
  # Set back the working directory to its original path
  setwd(wd.old)
}
